### ISSUE TITLE
[Bug] Blame doesn't work if path contains spaces

### ISSUE THREAD

**Issue by gamecentric** [ForkIssues/TrackerWin#177]
Similar to bug #62 except that this one is on Blame.
Bug present on v1.28.0.0 (Windows)

**Comment by DanPristupov** [comment]
Fixed in 1.29. Thank you!

**Comment by gamecentric** [comment]
I just updated to 1.29 and it seems that the bug is still present.

**Comment by DanPristupov** [comment]
OK, I'll double check tomorrow morning.

**Comment by gamecentric** [comment]
Still present in v1.29.1.0 (Win)

**Comment by DanPristupov** [comment]
Yes, sorry. Will be fixed in 1.30.

**Comment by gamecentric** [comment]
No problem, take your time :-)

**Comment by DanPristupov** [comment]
Fixed (again) :). Please check for updates.

**Comment by gamecentric** [comment]
Fix confirmed in 1.30.1
