### ISSUE TITLE
Filter branches - (Empty) section shouldn't be displayed when no item matches

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#412]
When filtering branches, if the typed filter matches a section name (Branches, Remotes, Tags, Stashes, Submodules) but that section is empty, the section name will be displayed while it shouldn't.

See for instance the following screenshots:

1. Filtering on "sta" while there are some stashes (but none matching "sta"): the section name is not displayed. ✔️ 
![image](https://user-images.githubusercontent.com/3851902/63842958-e321fe80-c985-11e9-82ac-164fbf1fd285.png)
2. Filtering on "sta" while there are no stashes: the section name is displayed. ❌
![image](https://user-images.githubusercontent.com/3851902/63842976-e74e1c00-c985-11e9-90d6-42e02007dd84.png)

**Comment by DanPristupov** [comment]
I think this is fixed already.

**Comment by Otiel** [comment]
No, using v1.47.0.0, I still see the "Stashes" section name when filtering on "sta" while there is no stashes.

**Comment by DanPristupov** [comment]
Strange. I can't reproduce that.

<img width="243" alt="Screenshot 2020-04-06 at 11 49 29" src="https://user-images.githubusercontent.com/618115/78545792-af049b00-77fc-11ea-89b0-e67427616689.png">

**Comment by DanPristupov** [comment]
Ah, ok. The must be no stashes.
