### ISSUE TITLE
issue with "Save commit as patch"

### ISSUE THREAD

**Issue by TheFerrango** [ForkIssues/TrackerWin#436]
When saving a commit as a patch, if the destination folder has a space in its name, the command returns an error and does not save the patch, prompting instead the following output:

```
fatal: ambiguous argument 'cartella': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

It's probably just the destination path needing to be in quotes. It works fine if the destination path has no spaces in it

**Comment by DanPristupov** [comment]
Fixed in 1.40. Please check for updates

**Comment by d1vanloon** [comment]
I still see this issue on version 1.41.1.0.

Is there any additional information I can provide?

**Comment by DanPristupov** [comment]
@d1vanloon reporting the problem is enough. Thanks.

**Comment by DanPristupov** [comment]
Fixed again in 1.42 :)
