### ISSUE TITLE
External diff: do not use a copy of the working file

### ISSUE THREAD

**Issue by Chadehoc** [ForkIssues/TrackerWin#47]
From the "Changes" view, external diff uses MyFile~remote and MyFile~local (a copy of the working file).

I often have to try several things in my working file, and then use external diff to review the change and edit the file (drop changes, move them, add comments where needed...). If I have to just keep or discard hunks I can use the indexing facilities, but I like the possibility to fully edit the working file. A copy does not allow it...

Note that from the "Commits" view, this copy is not made. I would like the "Changes" view to work the same way.

**Comment by DanPristupov** [comment]
Should be working properly in 1.26

**Comment by zrpfpr** [comment]
Still occurs in 1.26 using external diff in the Changes view. The $LOCAL file is a copy (the file ends with suffix ~local) and any modification made to the file is not reflected as a real change

**Comment by mjomble** [comment]
@zrpfpr did you test with a staged or unstaged file?

For me, external diff for an unstaged file opens the local file itself (not a copy), but external diff for a staged file opens a copy (with ~local suffix).
This makes sense as the staged content can be different from what's in the file system.

**Comment by zrpfpr** [comment]
You're right. I thought that if I modified something in a staged file, that modifications would appear as new changes in unstaged area. Thanks for the clarification!

**Comment by DanPristupov** [comment]
So, can I close the issue?
