### ISSUE TITLE
Wrong comment is editted in Interactive Rebase

### ISSUE THREAD

**Issue by elendil-software** [ForkIssues/TrackerWin#81]
Hi,

I found a bug in the Reword function in Interactive Rebase.

When the window is open, the first commit of the list is selected
![step1](https://user-images.githubusercontent.com/11425952/49948665-2e79a700-fef4-11e8-8b2e-c27b634cc1f9.png)

Then I select the option "Reword" on the last commit
![step2](https://user-images.githubusercontent.com/11425952/49948962-cd9e9e80-fef4-11e8-9992-7fe08305196e.png)

The edit box show up. I edit the commit message and click "OK".

Finally the window show that the first commit has been edited.
![step3](https://user-images.githubusercontent.com/11425952/49949001-e60eb900-fef4-11e8-941a-e151307374a7.png)

Regards

Julien

**Comment by DanPristupov** [comment]
Fixed in 1.26 :).

**Comment by elendil-software** [comment]
Hi,

I still have the same problem.
It looks like the selected menu option apply to the currently selected line.

Regards

Julien

**Comment by TanyaPristupova** [comment]
Sorry, we forgot to merge the fix into release. It will appear in the next update

**Comment by DanPristupov** [comment]
1.27 👍

**Comment by elendil-software** [comment]
Solved, Thanks !
